import {
  OPERATOR_CLAIM_URLS,
  OPERATOR_LABELS,
  TICKET_TYPE_LABELS,
  formatPounds,
  type Operator,
  type TicketType,
} from "@/lib/eligibility/dr15";

function formatWhen(iso: string): string {
  try {
    return new Date(iso).toLocaleString("en-GB", {
      dateStyle: "medium",
      timeStyle: "short",
      timeZone: "Europe/London",
    });
  } catch {
    return iso;
  }
}

export function buildClaimSummary(input: {
  operator: Operator;
  originName: string;
  destinationName: string;
  runDate: string;
  scheduledArrival: string;
  actualArrival: string;
  delayMinutes: number;
  ticketType: TicketType;
  ticketPricePence: number;
  compensationTier: string;
  compensationAmountPence: number;
}): string {
  const operatorName = OPERATOR_LABELS[input.operator];
  const claimUrl = OPERATOR_CLAIM_URLS[input.operator];

  return [
    `Delay Repay claim summary — ${operatorName}`,
    ``,
    `Journey date: ${input.runDate}`,
    `Route: ${input.originName} → ${input.destinationName}`,
    `Scheduled arrival: ${formatWhen(input.scheduledArrival)}`,
    `Actual arrival: ${formatWhen(input.actualArrival)}`,
    `Delay: ${input.delayMinutes} minutes (band ${input.compensationTier})`,
    ``,
    `Ticket: ${TICKET_TYPE_LABELS[input.ticketType]} — ${formatPounds(input.ticketPricePence)}`,
    `Compensation due: ${formatPounds(input.compensationAmountPence)}`,
    ``,
    `Claims must usually be submitted within 28 days of the journey.`,
    `Submit via: ${claimUrl}`,
    ``,
    `Generated by Fifteen — review before submitting to the operator.`,
  ].join("\n");
}
